export function resumeReportTemplate(report) {
  const renderList = (items) =>
    items?.length
      ? `<ul>${items.map((i) => `<li>${i}</li>`).join("")}</ul>`
      : "<p>No data available</p>";

  return `
  <div style="font-family: Arial; background:#0f0f0f; padding:24px; color:white">

    <h2 style="color:#a855f7">Resume Analysis Report</h2>
    <p><b>Overall Score:</b> ${report.overallScore}/100</p>

    <details>
      <summary style="cursor:pointer;color:#e9d5ff;font-size:18px">
        📊 Score Breakdown
      </summary>
      <ul>
        <li>ATS: ${report.scoreBreakdown.ats}</li>
        <li>Skills: ${report.scoreBreakdown.skills}</li>
        <li>Content: ${report.scoreBreakdown.content}</li>
      </ul>
    </details>

    <details>
      <summary style="cursor:pointer;color:#e9d5ff;font-size:18px">
        💪 Strengths
      </summary>
      ${renderList(report.strengths)}
    </details>

    <details>
      <summary style="cursor:pointer;color:#e9d5ff;font-size:18px">
        ⚠️ Weaknesses
      </summary>
      ${renderList(report.weaknesses)}
    </details>

    <details>
      <summary style="cursor:pointer;color:#e9d5ff;font-size:18px">
        🔥 High Impact Suggestions
      </summary>
      ${renderList(report.suggestions?.highImpact)}
    </details>

    <details>
      <summary style="cursor:pointer;color:#e9d5ff;font-size:18px">
        ⚡ Medium Impact Suggestions
      </summary>
      ${renderList(report.suggestions?.mediumImpact)}
    </details>

    <details>
      <summary style="cursor:pointer;color:#e9d5ff;font-size:18px">
        🟢 Low Impact Suggestions
      </summary>
      ${renderList(report.suggestions?.lowImpact)}
    </details>

    <details>
      <summary style="cursor:pointer;color:#e9d5ff;font-size:18px">
        ✍ Grammar & Formatting
      </summary>
      ${renderList(report.grammarAndFormatting?.suggestions)}
    </details>

    <hr />
    <p style="color:#999">Generated by Resume AI</p>

  </div>
  `;
}
